# Generated by Django 2.0.3 on 2018-05-15 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import wiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('published', models.BooleanField(default=False, verbose_name='公開する')),
                ('feature_name', models.CharField(default='No place', max_length=128)),
                ('gis_type', models.CharField(default='No GIS type', max_length=32)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('title', models.CharField(max_length=48, verbose_name='記事タイトル')),
                ('summary', models.CharField(max_length=128, verbose_name='記事の概要')),
                ('body', tinymce.models.HTMLField(verbose_name='本文')),
                ('soya_certified', models.BooleanField(default=False, help_text='Certified', verbose_name='認証済')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('body', models.TextField(verbose_name='本文')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.Article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WikiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('published', models.BooleanField(default=False, verbose_name='公開')),
                ('title', models.CharField(default='', max_length=128, verbose_name='タイトル')),
                ('summary', models.CharField(default='', max_length=256, verbose_name='概要')),
                ('md5', models.CharField(default='', max_length=32, verbose_name='md5')),
                ('upload', models.ImageField(upload_to=wiki.models.user_directory_path, verbose_name='画像や写真')),
                ('author', models.ForeignKey(default=False, on_delete='投稿者', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(default=wiki.models.default_category_m2m, to='wiki.Category', verbose_name='カテゴリ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='wiki.Category', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='article',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.Feature'),
        ),
    ]
