# Generated by Django 2.0.2 on 2018-02-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
