# Generated by Django 2.0.3 on 2018-05-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.Period', verbose_name='年代'),
        ),
    ]
