# Generated by Django 2.0.2 on 2018-02-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_feature'),
        ('wiki', '0002_delete_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.Feature'),
        ),
    ]
