# Generated by Django 2.0.2 on 2018-02-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20180217_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
