# Generated by Django 2.0.3 on 2018-03-09 05:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20180220_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='本文'),
        ),
    ]
