# Generated by Django 2.0.3 on 2018-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20180309_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='landmark',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
    ]
