# Generated by Django 2.0.2 on 2018-02-12 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm1920',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1950',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1955',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1960',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1980',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1985',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm1995',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=14)),
                ('begin', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm2005',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=8)),
                ('sub_pref', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=12)),
                ('begin', models.CharField(max_length=1)),
                ('end', models.CharField(max_length=1)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=10)),
                ('sub_pref', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='Adm2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=10)),
                ('sub_pref', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('adm_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='RailroadSection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=1)),
                ('rail_name', models.CharField(max_length=28)),
                ('company', models.CharField(max_length=30)),
                ('supplied_in', models.CharField(max_length=4)),
                ('operated_from', models.CharField(max_length=4)),
                ('operated_to', models.CharField(max_length=4)),
                ('relation_id', models.CharField(max_length=10)),
                ('transition_id', models.CharField(max_length=1)),
                ('transition_note', models.CharField(max_length=1)),
                ('note', models.CharField(max_length=40)),
                ('relation_note', models.CharField(max_length=21)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4612)),
            ],
        ),
        migrations.CreateModel(
            name='RailroadStation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=1)),
                ('rail_name', models.CharField(max_length=28)),
                ('company', models.CharField(max_length=30)),
                ('supplied_in', models.CharField(max_length=4)),
                ('operated_from', models.CharField(max_length=4)),
                ('operated_to', models.CharField(max_length=4)),
                ('relation_id', models.CharField(max_length=13)),
                ('transition_id', models.CharField(max_length=1)),
                ('transition_note', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=40)),
                ('station_name', models.CharField(max_length=35)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4612)),
            ],
        ),
    ]
