# Generated by Django 2.0.3 on 2018-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
